### PR TITLE
fix(PageSection): updated logic to account for variant enum

### LINKED ISSUE #633: PageSection - PageSectionVariants enum isn't picked up by the PageSection variant prop codemod
The PageSection variant prop codemod does not detect usage of the PageSectionVariant enum, ideally it would both detect and auto fix the variant prop appropriately.

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

### PR DESCRIPTION
**Pull request by thatblindgeye**
Closes #633

### CODE REVIEW

**Review by wise-king-sullyman — APPROVED** [review]

File: packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionUpdateVariantValues/pageSection-update-variant-values.ts [hunk 1]
```diff
@@ -22,28 +25,38 @@ module.exports = {
...
+                variantValue.object.name === pageSectionVariantLocalName;
 
-              if (!attribute || !attribute.value) {
+              if (variantProp.value.type !== "Literal" && !hasPatternFlyEnum) {
                 return;
               }
+              const hasValidValue = variantValue.property
+                ? validValues.includes(variantValue.property.name)
+                : validValues.includes(variantValue);
+              console.log(hasValidValue);
```
Comment (adamviktora) [inline packages/eslint-plugin-pf-codemods/src/rules/v6/pageSectionUpdateVariantValues/pageSection-update-variant-values.ts:49]: nit: forgotten console.log
```suggestion
```

**Review by adamviktora — APPROVED** [review]
🎉
