### PR TITLE
fix(CardHeader): updated logic to take into account conditional rendering

### LINKED ISSUE #524: CardHeader - API update not working with conditional rendering
The `cardHeader-update-api` codemod doesn't work as intended when CardActions is conditionally rendered (most likely the same for CardHeaderMain). A structure like the following won't be updated (though the imports *will* be removed):

```
<CardHeader>
   {dropdownItems && <CardActions />}
</CardHeader>
```

### PR DESCRIPTION
**Pull request by thatblindgeye**
Closes #524 

@gitdallas this runs into the possible issue that the test file has a "first run" and "second run" test due to the way the fix works. Testing in the `test.tsx` file things look to work as intended, though.

### CODE REVIEW

File: packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js [hunk 1]
```diff
@@ -8,142 +8,146 @@ module.exports = {
...
+        return isCardHeaderMainContent
+          ? `{${conditionalTestContent} ? ${content} : ${conditionalAlternateContent}}`
+          : `actions={${conditionalTestContent} ? ${content} : {}}`;
+      }
+    };
 
     return ![...removedCardImports, cardHeaderImport].length
       ? {}
       : {
-          ImportDeclaration(node) {
```
Comment (thatblindgeye) [inline packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js:16]: Removing the imports should be taken care of by the no unused import rule, so we don't really need to handle that logic here.

File: packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js [hunk 2]
```diff
@@ -8,142 +8,146 @@ module.exports = {
     const removedCardImports = imports.filter((specifier) =>
       ["CardHeaderMain", "CardActions"].includes(specifier.imported.name)
     );
-    const cardHeaderImport = imports.find((specifier) => specifier.imported.name === "CardHeader");
+    const cardHeaderImport = imports.find(
+      (specifier) => specifier.imported.name === "CardHeader"
+    );
+
+    const findParents = (node, elementNameToFind) => {
```
Comment (gitdallas) [inline packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js:15]: wonder if this should be a helper func

File: packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js [hunk 3]
```diff
@@ -8,142 +8,146 @@ module.exports = {
...
+      const parents = {
+        current: node?.parent,
```
Comment (gitdallas) [inline packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js:17]: current makes sense for the loop internal to this function but i'm not sure it makes sense as the return type - maybe more important if we did make this a helper func

also, should it be findParent() or findClosestParent() maybe as we are only going to return as soon as we find what we are looking for and not have an array of parents... or i suppose plural is because you are also finding the expression as a parent.. 

i suppose i'm showing my thoughts as i'm thinking and reading through this. it makes sense to me now, might make sense to just be overly verbose `getExpressionAndParentCardHeader` as that is all we are doing with this function and i think i'd go with `parent` instead of `current`.

but really all these words are just for a nit at this point 🤣

File: packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js [hunk 4]
```diff
@@ -8,142 +8,146 @@ module.exports = {
...
+        ) {
+          parents.conditionalExpression = parents.current;
+        }
+
+        parents.current = parents.current.parent;
+      }
+
+      return undefined;
+    };
+    const getComponentContent = (component) => {
```
Comment (gitdallas) [inline packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js:38]: is there no `innerHTML` or equivalent that could have achieved the same?

**Review by gitdallas — APPROVED** [review]
looks thorough and good, if anything maybe it could be a little more readable.. but pretty impressive you were able to whip this up as quick as you did

File: packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (thatblindgeye) [reply packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js:15]: Yeah I considered it, but for now since it's for this specific use case didn't think we really needed it.

File: packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js (hunk 3 above)
Comment (thatblindgeye) [reply packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js]: Makes sense, I updated the naming of things for this. Let me know what you think

File: packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js (hunk 4 above)
Comment (thatblindgeye) [reply packages/eslint-plugin-pf-codemods/lib/rules/v5/cardHeader-update-api.js]: Replaced it with just mapping over the node children to `getText` instead

**Review by wise-king-sullyman — APPROVED** [review]
