### PR TITLE
fix(TextReplaceWithContent): update dist import path

### LINKED ISSUE #791: The Text -> Content codemod seems to not update dist import paths appropriately
Running the codemod updated the Text component import and usage appropriately, but it did not update the import path

Image

### PR DESCRIPTION
**Pull request by adamviktora**
Closes #791

### CODE REVIEW

File: packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.ts [hunk 1]
```diff
@@ -71,11 +71,28 @@ module.exports = {
               const specifierName = specifierToReplace.imported.name;
               const newText = getNewText(specifierName);
 
+              const importPath = node.source.value?.toString() as string;
```
Comment (wise-king-sullyman) [inline packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.ts:74]: Is there a way to do this without the type assertion? If not is this type assertion truly safe?

It seems like `importPath` could potentially resolve as undefined here.

Comment (adamviktora) [reply packages/eslint-plugin-pf-codemods/src/rules/v6/textReplaceWithContent/text-replace-with-content.ts:74]: I mean, technically it should always be a string starting with `"@patternfly/react-core"`, but I'll update it so there is not the casting

**Review by thatblindgeye — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]
🚀
