### PR TITLE
fix(move specifiers) keep inputkind while moving specifiers

### LINKED ISSUE #512: 'type' keyword not preserved when updating path
When importing with `type`, the keyword gets removed after updating the path via moveSpecifiers.

eg.
`import type { someType } from "@patternfly/react-core"`  turns into
`import { someType } from "@patternfly/react-core/deprecated"`

### PR DESCRIPTION
**Pull request by gitdallas**
closes #512

### CODE REVIEW

**Review by thatblindgeye — APPROVED** [review]

File: packages/eslint-plugin-pf-codemods/lib/helpers.js [hunk 1]
```diff
@@ -74,7 +74,10 @@ function moveSpecifiers(
         return (
           node?.type === nodeType &&
           [modifiedPackage, toPackage].includes(node?.source?.value) &&
-          specifierReference?.parent?.importKind === node?.importKind
+          (
+            specifierReference?.parent?.importKind === node?.importKind &&
+            specifierReference?.parent?.exportKind === node?.exportKind
```
Comment (gitdallas) [inline packages/eslint-plugin-pf-codemods/lib/helpers.js:79]: i figured i'd just do && here rather than checking if we are dealing with import or export and then checking that one... this works because if we are dealing with an import... exportKind will be undefined in both places and vice versa

**Review by thatblindgeye — APPROVED** [review]
